### ISSUE TITLE
Why Is This Plugin Maintained?

### ISSUE THREAD

**Issue by opticyclic** [JetBrains/intellij-feature-suggester#12]
This plugin was created _after_ Key Promoter X and has fewer features.
Key Promoter X has a higher rating and tons more downloads.
https://plugins.jetbrains.com/plugin/9792-key-promoter-x

Aren't you just wasting JetBrains developer time that could be used elsewhere?
Or if you have time to work on this, why wouldn't you just contribute to Key Promoter X instead?

**Comment by yole** [comment]
This plugin has completely different functionality than Key Promoter X. Key Promoter X notifies you when you're invoking an action using the mouse instead of a keyboard shortcut. This plugin notifies you when you're doing something manually instead of using an IDE action.
