### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by Quasilyte** [JetBrains/intellij-feature-suggester#4]
This repository misses the license file.
The severity of that varies from project to project, but my goal here is to attract some attention.

If it's not a problem, this issue can be closed.

I'm leaving it here just in case: https://help.github.com/articles/adding-a-license-to-a-repository/.

Thanks.

**Comment by yusuke** [comment]
Any update on this?
I'm thinking of localizing this project, but the license needs to be defined before that.

**Comment by Alefas** [comment]
I just added Apache 2.0 license, sorry for the delay.
